package com.exadel.tenderflex.repository.entity;

public enum ERolePrivilege {
    CAN_READ_TENDER, CAN_CREATE_OFFER, CAN_READ_OFFER, CAN_READ_CONTRACT_STATUS, CAN_READ_CONTRACT_PDF,
    CAN_APPROVE_DECLINE_CONTRACT, CAN_CREATE_AND_PUBLISH_TENDER, CAN_ACCEPT_DECLINE_OFFER, CAN_UPLOAD_CONTRACT
}
