package com.exadel.tenderflex.repository.entity.enums;

public enum EOfferStatus {
    OFFER_HAS_NOT_SEND ,OFFER_SENT, OFFER_RECEIVED, OFFER_REJECTED_BY_CONTRACTOR, OFFER_SELECTED_BY_CONTRACTOR,
    CONTRACT_DECLINED_BY_BIDDER, CONTRACT_APPROVED_BY_BIDDER
}
